services:
  web:
    build: .
    container_name: stockmonitor-web
    ports:
      - "5010:5000"
    env_file:
      - .env
    volumes:
      - ./instance:/app/instance
      - ./parsers:/app/parsers
    restart: unless-stopped
